// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAWfUvvBF-8SGrA6ENwtz1nNMnSIwU2Z8',
    appId: '1:833020376717:web:b85f76300fd87e444114c4',
    messagingSenderId: '833020376717',
    projectId: 'wasacricket-4bb6c',
    authDomain: 'wasacricket-4bb6c.firebaseapp.com',
    storageBucket: 'wasacricket-4bb6c.firebasestorage.app',
    measurementId: 'G-ZKYNFENBGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlP_iFZhe1SxKRrME9BvHwIkmI9SPn_8o',
    appId: '1:833020376717:android:e3d45f357397119c4114c4',
    messagingSenderId: '833020376717',
    projectId: 'wasacricket-4bb6c',
    storageBucket: 'wasacricket-4bb6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAgWBoFAPi6Jz14mIGDC8a88XTVu4uajw',
    appId: '1:833020376717:ios:173244785e1f70164114c4',
    messagingSenderId: '833020376717',
    projectId: 'wasacricket-4bb6c',
    storageBucket: 'wasacricket-4bb6c.firebasestorage.app',
    iosClientId: '833020376717-beos6o33t16rjg0hmau75sf8u9tbdrc5.apps.googleusercontent.com',
    iosBundleId: 'com.wpl.wplCricketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAgWBoFAPi6Jz14mIGDC8a88XTVu4uajw',
    appId: '1:833020376717:ios:173244785e1f70164114c4',
    messagingSenderId: '833020376717',
    projectId: 'wasacricket-4bb6c',
    storageBucket: 'wasacricket-4bb6c.firebasestorage.app',
    iosClientId: '833020376717-beos6o33t16rjg0hmau75sf8u9tbdrc5.apps.googleusercontent.com',
    iosBundleId: 'com.wpl.wplCricketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAWfUvvBF-8SGrA6ENwtz1nNMnSIwU2Z8',
    appId: '1:833020376717:web:bc4b937e30dd65bc4114c4',
    messagingSenderId: '833020376717',
    projectId: 'wasacricket-4bb6c',
    authDomain: 'wasacricket-4bb6c.firebaseapp.com',
    storageBucket: 'wasacricket-4bb6c.firebasestorage.app',
    measurementId: 'G-P9Q43XTZK9',
  );
}
